name: stm_extensions
version: 0.1.2

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
flutter: